config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "products#index"
  resources :expiration_usages
  resources :expiration_dates
  resources :ratings
  resources :reviews
  resources :categories
  resources :brands
  resources :product_images
  resources :products
  resources :products_searches
  resources :used_copons
  resources :copons
  resources :wish_lists
  resources :order_states
  resources :orders
  resources :shopping_carts
  resources :stores

  get '/myorders', to: 'orders#get_seller_orders', as: 'seller_orders'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_state.rb
class OrderState < ApplicationRecord
end

app/controllers/order_states_controller.rb
class OrderStatesController < ApplicationController
  before_action :set_order_state, only: [:show, :edit, :update, :destroy]

  # GET /order_states
  # GET /order_states.json
  def index
    @order_states = OrderState.all
  end

  # GET /order_states/1
  # GET /order_states/1.json
  def show
  end

  # GET /order_states/new
  def new
    @order_state = OrderState.new
  end

  # GET /order_states/1/edit
  def edit
  end

  # POST /order_states
  # POST /order_states.json
  def create
    @order_state = OrderState.new(order_state_params)

    respond_to do |format|
      if @order_state.save
        format.html { redirect_to @order_state, notice: 'Order state was successfully created.' }
        format.json { render :show, status: :created, location: @order_state }
      else
        format.html { render :new }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_states/1
  # PATCH/PUT /order_states/1.json
  def update
    respond_to do |format|
      if @order_state.update(order_state_params)
        format.html { redirect_to @order_state, notice: 'Order state was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_state }
      else
        format.html { render :edit }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_states/1
  # DELETE /order_states/1.json
  def destroy
    @order_state.destroy
    respond_to do |format|
      format.html { redirect_to order_states_url, notice: 'Order state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_state
      @order_state = OrderState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_state_params
      params.fetch(:order_state, {})
    end
end

app/helpers/order_states_helper.rb
module OrderStatesHelper
end

app/views/order_states/_form.html.erb
<%= form_with(model: order_state, local: true) do |form| %>
  <% if order_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_state.errors.count, "error") %> prohibited this order_state from being saved:</h2>

      <ul>
      <% order_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_states/edit.html.erb
<h1>Editing Order State</h1>

<%= render 'form', order_state: @order_state %>

<%= link_to 'Show', @order_state %> |
<%= link_to 'Back', order_states_path %>

app/views/order_states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order States</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_states.each do |order_state| %>
      <tr>
        <td><%= link_to 'Show', order_state %></td>
        <td><%= link_to 'Edit', edit_order_state_path(order_state) %></td>
        <td><%= link_to 'Destroy', order_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order State', new_order_state_path %>

app/views/order_states/new.html.erb
<h1>New Order State</h1>

<%= render 'form', order_state: @order_state %>

<%= link_to 'Back', order_states_path %>

app/views/order_states/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_state_path(@order_state) %> |
<%= link_to 'Back', order_states_path %>