config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "products#index"
  resources :expiration_usages
  resources :expiration_dates
  resources :ratings
  resources :reviews
  resources :categories
  resources :brands
  resources :product_images
  resources :products
  resources :products_searches
  resources :used_copons
  resources :copons
  resources :wish_lists
  resources :order_states
  resources :orders
  resources :shopping_carts
  resources :stores

  get '/myorders', to: 'orders#get_seller_orders', as: 'seller_orders'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :brand
    belongs_to :category
    belongs_to :user    # seller
    has_many_attached :images
    has_many :orders
    has_one :copon

    validates :title, :presence => true, length: { minimum: 5 }
    validates :description, :presence => true, length: { minimum: 10 }
    validates :quantity, :presence => true
    validate :seller_existance
     
    
   
    validate :images_types

    def self.get_all_products
        Product.all
    end

    def self.get_products_count
        Product.all.length
    end

    def self.get_by_id(id)
        Product.find(id)
    end

    def self.search(criteria)
        if criteria
            where("title LIKE ? or description LIKE ?", "%#{criteria}%", "%#{criteria}%")
        else
            all
        end
    end

    def self.get_products_with_no_copons(except)
        products = []
        Product.all.each do |p|
            if p.copon && p.copon.is_expired
                p.copon = nil
            end
            if p.copon
                if except && p.id == except.id
                    products.append(p)
                end
            else
                products.append(p)
            end
        end
        products
    end

    private
        def seller_existance
            if user.role != 'seller'
                errors.add(:product, 'can be added only by sellers')
            end 
        end

        def images_types
            if images.attached?
                images.each do |image|
                    unless image.content_type.in?(%('image/jpeg image/png'))
                        errors.add(:images, "have not supported format, only JPEG and PNG are supported")
                    end
                end
            else
                errors.add(:images, "are missing")
            end
        end
        
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
 

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    product_associatives(@product, params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    product_associatives(@product, params[:product])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :quantity, :title, :description, images: [])
    end

    def product_associatives(product, parameters)
      product.user = current_user
      product.brand = Brand.find(parameters[:brand])
      product.category = Category.find(parameters[:category])
    end
   
end

app/helpers/products_helper.rb
module ProductsHelper
    
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.select(:brand) do %>
      <% brands_array = Brand.all.collect { |b| [b.name, b.id] } %>
      <% if product && product.brand %>
        <%= options_for_select(brands_array, :selected => product.brand.id) %>
      <% else %>
        <%= options_for_select(brands_array) %>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category) do %>
      <% categories_array = Category.all.collect { |c| [c.name, c.id] } %>
      <% if product && product.category %>
        <%= options_for_select(categories_array, :selected => product.category.id) %>
      <% else %>
        <%= options_for_select(categories_array) %>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, :min => 1, step: :any %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, :min => 0 %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<h1>All Products</h1>
<% if current_user %>
 <% if !can? :edit, Product %>
<%= link_to "mycart", orders_path %>
<%end%>
<%end%>

 <% if can? :edit, Product %>
<td><%= link_to 'Orders', seller_orders_path()%></td>
<%end%>
<%= form_tag products_path, :method => 'get' do %>
  <strong>
    Search by title or description (leave it blank to get all products) or 
    <%= link_to "Filter products", new_products_search_path %>:
  </strong>
  <div class="search-bar">
    <%= text_field_tag :search, params[:search] %>
  </div>
  <br>
  
  <br><br>
<% end %>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Quantity</th>
      <th>Title</th>
      <th>Description</th>
      <th>Seller</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Images</th>
      <th>Copon</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.user.name %></td>
        <td><%= product.category.name %></td>
        <td><%= product.brand.name %></td>
        <td>
          <div>
            <% product.images.each do |image| %>
              <%= image_tag image, width: '80px', height: '80px' %>
            <% end %>
          </div>
        </td>
        <td>
      <% if product.copon && !product.copon.is_expired %>
            <%= product.copon.discount %>
            <%= product.copon.get_symbol %>
          <% else %>
            <%= "None" %>
          <% end %>
        </td>
             <td><%= link_to 'Show', product %></td>
        <% if can? :edit, Product %>
        
   
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <%end%>
        <% if can? :destroy, Product %>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
      
        <% if product.quantity > 0 %>
        <td><%= link_to "Add To Cart", orders_path(product.id), :method => :post %>
        <%end%>
      
       
       
      </tr>
    <% end %>
  </tbody>
</table>



<br>
<% if can? :create, Product %>
<%= link_to 'New Product', new_product_path %>
<%end%>

app/views/products/new.html.erb
<% if current_user %>
  <% User.assign_role(current_user, 'seller') %>
<% end %>
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Images:</strong>
  <br>
  <% @product.images.each do |image| %>
    <%= image_tag image, width: '200px', height: '200px' %>
  <% end %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @product.user.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>


<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<% if @product.copon && !@product.copon.is_expired %>
  <p>  
    <strong>Copon:</strong>
    <%= @product.copon.discount %>
    <%= @product.copon.get_symbol %>
    <% if @product.copon.is_available_for(current_user) %>
      <button name="use_copon_btn" id="<%= @product.copon.id %>">use this copon </button>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>